import type { Product, ProductImage } from "./products";

/**
 * CRETEM product data.
 * Source of truth: "OUR PRODUCTS" brochure pages and CRETEM PDFs.
 * Images: public/products/cretem (converted from "Product images/CRETEM Product Pictures").
 */

const IMG = "/products/cretem";

const POWER_SUPPLY = "220V/60Hz (Korea) · 120V/60Hz (US) · 230–240V/50Hz (Europe)";

// Shared platform close-ups used across the FS-series packagers.
const platformImages = {
  fspSlim: { src: `${IMG}/fsp-02.webp`, alt: "Free Shape Packing (FSP) unit drawn out from a CRETEM packager", caption: "FSP — Free Shape Packing unit" } satisfies ProductImage,
  fspDetail: { src: `${IMG}/fsp-03.webp`, alt: "Close-up of the FSP rotary hopper on a CRETEM packager", caption: "FSP hopper for free-shape and half tablets" } satisfies ProductImage,
  fspDetailAlt: { src: `${IMG}/fsp-04.webp`, alt: "FSP module with digital cell indicator", caption: "FSP module with cell indicator" } satisfies ProductImage,
  fspFront: { src: `${IMG}/fsp-01.webp`, alt: "FSP drawer open on a CRETEM packager showing the rotary hopper", caption: "FSP drawer, open" } satisfies ProductImage,
  mdu30: { src: `${IMG}/mdu-30-cell.webp`, alt: "30-cell Manual Divide Unit tray with tablets loaded", caption: "MDU — 30-cell Manual Divide Unit" } satisfies ProductImage,
  cassetteDrawer: { src: `${IMG}/cassette-03.webp`, alt: "T-slide drawer extended with numbered drug cassettes", caption: "T-slide drawer with drug cassettes" } satisfies ProductImage,
  cassetteReplenish: { src: `${IMG}/cassette-01.webp`, alt: "Technician replenishing a drug cassette on the T-slide drawer", caption: "Easy replenishment on the T-slide system" } satisfies ProductImage,
  cassetteReplenishAlt: { src: `${IMG}/cassette-02.webp`, alt: "Technician brushing a drug cassette on the extended drawer", caption: "Cassette cleaning and refill from the front" } satisfies ProductImage,
  lowerUnit: { src: `${IMG}/lower-unit.webp`, alt: "Printing and packing system inside the lower cabinet with wrapping paper roll", caption: "Printing & packing system, lower cabinet" } satisfies ProductImage,
  canisters: { src: `${IMG}/canisters.webp`, alt: "Three CRETEM canisters with barcode labels", caption: "CRETEM canisters with barcode ID", fit: "contain" } satisfies ProductImage,
};

// Component labels common to the FS-series diagrams in the brochure.
const fsComponents = {
  drugCassette: { name: "Drug cassette", description: "Dedicated cassette per medication, installed in each single drawer of the cabinet." },
  fndCassette: { name: "FND cassette", description: "FND cassette positions for high-frequency medications in the upper cabinet." },
  tSlide: { name: "T-slide system", description: "The advanced T-slide technology lets staff draw cassettes forward for easy replenishment." },
  controlPanel: { name: "Control panel", description: 'Industrial PC with a Windows 10 touch screen (10.1") for order input and system control.' },
  mdu: { name: "MDU — Manual Divide Unit", description: "Cell tray for manually divided medications that are not assigned to a cassette." },
  fsp: { name: "FSP — Free Shape Packing unit", description: "Packs free-shape and half tablets that do not fit a standard cassette. A dedicated FSP printer labels FSP output." },
  eStop: { name: "E-Stop button", description: "Front-panel emergency stop." },
  sound: { name: "Sound message", description: "Audio status messages during operation." },
  printing: { name: "Printing & packing system", description: "Thermal-transfer printing and pouch sealing in the lower cabinet; no limit to the number of characters or font size." },
  pouchOutlet: { name: "Pouch outlet", description: "Finished pouches exit at the front of the lower cabinet." },
};

const fsWorkflow = [
  { title: "Order received", description: "Prescriptions arrive through the OCS linkage or are entered directly on the Windows 10 touch screen." },
  { title: "Cassettes dispense", description: "Each tablet is dispensed from its dedicated drug cassette and verified by infrared photodetection." },
  { title: "FSP and MDU add non-cassette items", description: "Free-shape and half tablets are packed by the FSP unit; manually divided medications are loaded via the MDU tray." },
  { title: "Pouch is printed and sealed", description: "The printing & packing system thermal-prints the wrapper — no character or font-size limit — and seals each pouch." },
  { title: "Pouches exit", description: "Unit-dose or multi-dose pouches leave through the pouch outlet at up to 60 pouches per minute." },
];

const fsIntegration = [
  "OCS (Order Communication System) linkage",
  "Internal order input on the touch screen",
  "Windows 10 industrial PC control",
];

export const cretemProducts: Product[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // CAP(EX) MODEL
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: "cap-ex-model",
    manufacturer: "CRETEM",
    category: "Pouch packaging",
    name: "CAP(EX) Model",
    seriesName: "CAP(EX)-52FS · 72FS · 92FS",
    tagline: "Extendable Intelligent Tablet Packing System",
    heroImage: `${IMG}/cap-ex-92fs.webp`,
    heroImageAngled: `${IMG}/ex-92fs.webp`,
    heroCaption: "Pictured: CAP(EX)-92FS",
    description:
      "The CAP(EX) Model is CRETEM's extendable cassette packager with 3 Free Shape Packing (FSP) units on every size. Start with 52 cassettes in a 670 mm-wide cabinet and grow in place to 72 or 92 cassettes by adding cassette blocks — the control, FSP and printing systems stay the same. Every configuration also runs a 30-cell Manual Divide Unit, infrared photodetection and thermal-transfer pouch printing at up to 60 unit-dose pouches per minute.",
    heroStats: [
      { value: "3", label: "FSP units", note: "Standard on every size" },
      { value: "52–92", label: "Cassettes", note: "Extendable in place" },
      { value: "60", label: "Pouches / min", note: "Max unit dose · avg 55 multi dose" },
      { value: "670 mm", label: "Cabinet width", note: "490 mm deep" },
    ],
    valueProps: [
      { title: "3 FSP units on every CAP(EX)", description: "Three Free Shape Packing units are standard on the 52FS, 72FS and 92FS — the highlighted packing path for half tablets and irregular shapes that do not fit a cassette." },
      { title: "Buy for today, extend for tomorrow", description: "CAP(EX)-52FS grows to 72FS and 92FS by adding 20-cassette blocks on the same base and control unit, so capacity follows your formulary instead of forcing a replacement." },
      { title: "Compact footprint", description: "At 670 × 490 mm, every CAP(EX) configuration shares the same floor area — only the height changes (1,560 / 1,740 / 1,910 mm)." },
    ],
    howItWorks:
      "Prescriptions arrive through the OCS linkage or internal input on the 10.1-inch Windows 10 touch screen. Tablets are dispensed from dedicated cassettes and verified by infrared photodetection. Free-shape and half tablets run through the three FSP units, and manually divided medications are loaded via the 30-cell MDU. The printing & packing system thermal-prints and seals 75 mm × 70 mm pouches (55 mm × 50 mm by order), which exit at the pouch outlet.",
    workflow: fsWorkflow,
    gallery: [
      platformImages.fspSlim,
      platformImages.fspDetail,
      { src: `${IMG}/cap-ex-series.webp`, alt: "CAP-72FS, CAP-92FS and CAP-52FS packagers installed in a pharmacy", caption: "CAP(EX) series — 72FS, 92FS and 52FS in a pharmacy setting", fit: "contain" },
      { src: `${IMG}/cap-ex-extendable.webp`, alt: "Extension path from CAP-52FS to CAP-52FS+20, CAP-72FS and CAP-92FS", caption: "Extension path: CAP-52FS → +20 → CAP-72FS → CAP-92FS", fit: "contain" },
      platformImages.mdu30,
      platformImages.cassetteDrawer,
      platformImages.lowerUnit,
    ],
    modules: [
      { name: "Free Shape Packing", abbreviation: "FSP", availability: "3 units on every model", featured: true, description: "The highlighted module on the CAP(EX) series. Three rotary FSP hoppers on every size pack free-shape and half tablets that do not fit a standard cassette, with a dedicated FSP printer.", image: platformImages.fspSlim },
      { name: "Manual Divide Unit", abbreviation: "MDU", availability: "30-cell tray", description: "Numbered 30-cell tray for medications added by hand, so non-cassette items still travel through the same pouch sequence.", image: platformImages.mdu30 },
      { name: "T-slide cassette system", abbreviation: "T-slide", availability: "Standard", description: "Cassette drawers slide forward for replenishment from the front of the cabinet, without pulling a full drawer stack.", image: platformImages.cassetteReplenish },
    ],
    anatomy: [
      fsComponents.drugCassette,
      fsComponents.fndCassette,
      fsComponents.tSlide,
      { name: "Easy replenishment", description: "Cassettes are refilled from the cabinet face via the T-slide drawers." },
      fsComponents.controlPanel,
      fsComponents.mdu,
      fsComponents.fsp,
      fsComponents.eStop,
      fsComponents.sound,
      fsComponents.printing,
      fsComponents.pouchOutlet,
    ],
    modelTable: {
      models: ["CAP(EX)-52FS", "CAP(EX)-72FS", "CAP(EX)-92FS"],
      rows: [
        { label: "No. of cassettes", values: ["52", "72", "92"] },
        { label: "Cassette types (S / M / L)", values: ["12 / 20 / 20", "32 / 20 / 20", "52 / 20 / 20"] },
        { label: "Block structure", values: ["A + C + B", "A + A + C + B", "A + A + A + C + B"] },
        { label: "FSP", values: ["3 units", "3 units", "3 units"] },
        { label: "MDU", values: ["30 cell", "30 cell", "30 cell"] },
        { label: "Main body (W × D × H, mm)", values: ["670 × 490 × 1,560", "670 × 490 × 1,740", "670 × 490 × 1,910"] },
        { label: "Weight", values: ["200 kg", "225 kg", "250 kg"] },
      ],
    },
    specs: [
      { label: "No. of cassettes", value: "52 / 72 / 92 (by model)" },
      { label: "Means of control", value: 'Windows 10, touch screen 10.1"' },
      { label: "Refinement & detection", value: "Infrared photodetection" },
      { label: "Drug storage", value: "Cabinet type with cassettes installed in each single drawer" },
      { label: "Dispensing speed", value: "Max 60 unit-dose pouches/min · avg 55 multi-dose pouches/min" },
      { label: "Printing on the wrapper", value: "Thermal transfer — no limit to the number of characters or font size" },
      { label: "Wrapping paper size", value: "75 mm × 70 mm, or 55 mm × 50 mm by order" },
      { label: "Input", value: "OCS linkage or internal input" },
      { label: "FSP", value: "3 units" },
      { label: "MDU", value: "30 cell" },
      { label: "Main body (W × D × H)", value: "670 × 490 × 1,560 / 1,740 / 1,910 mm" },
      { label: "Weight", value: "200 / 225 / 250 kg" },
      { label: "Power consumption", value: "200W (max 600W)" },
    ],
    highlights: [
      { title: "3 FSP units standard", description: "Three Free Shape Packing units on every size — the highlighted packing path for half tablets and irregular shapes." },
      { title: "Extendable in 20-cassette steps", description: "Grow from CAP(EX)-52FS to 72FS to 92FS by adding cassette blocks (A + C + B → A + A + C + B → A + A + A + C + B)." },
      { title: "60 pouches per minute", description: "Maximum 60 unit-dose pouches per minute and an average of 55 pouches per minute on multi-dose runs." },
      { title: "30-cell MDU", description: "Manual Divide Unit tray for medications that are not assigned to a cassette." },
      { title: "Infrared photodetection", description: "Every tablet is optically detected as it is dispensed." },
      { title: "Unlimited thermal printing", description: "Thermal-transfer wrapper printing with no character or font-size limit." },
      { title: "670 mm wide", description: "The same 670 × 490 mm footprint across all three configurations." },
      { title: "OCS or internal input", description: "Receive orders from the order communication system or enter them on the touch screen." },
    ],
    features: [
      "3 Free Shape Packing (FSP) units with FSP printer — standard on every size",
      "Extendable structure: 52 → 72 → 92 cassettes on the same base",
      "Cabinet-type storage with cassettes in each single drawer",
      "T-slide system for easy replenishment",
      'Windows 10 control with 10.1" touch screen',
      "Infrared photodetection on every dispensed tablet",
      "30-cell Manual Divide Unit",
      "Thermal-transfer printing, 75 × 70 mm or 55 × 50 mm wrapper",
    ],
    integration: fsIntegration,
    useCases: ["Community and retail pharmacies", "Hospital satellite pharmacies", "Growing adherence programs"],
    faqs: [
      { question: "Does every CAP(EX) include FSP?", answer: "Yes. Three Free Shape Packing (FSP) units are standard on CAP(EX)-52FS, 72FS and 92FS, with a dedicated FSP printer. FSP packs half tablets and irregular shapes that do not fit a cassette. Every size also includes a 30-cell Manual Divide Unit." },
      { question: "How does the CAP(EX) extend from 52 to 92 cassettes?", answer: "Cassette blocks are added to the existing unit. CAP(EX)-52FS is an A + C + B structure; adding one A block gives CAP(EX)-72FS (A + A + C + B) and a second gives CAP(EX)-92FS (A + A + A + C + B). Width and depth stay 670 × 490 mm; height increases from 1,560 to 1,740 to 1,910 mm." },
      { question: "What is the cassette mix on each model?", answer: "CAP(EX)-52FS: 12 small, 20 medium, 20 large. CAP(EX)-72FS: 32 small, 20 medium, 20 large. CAP(EX)-92FS: 52 small, 20 medium, 20 large." },
      { question: "How fast does it pack?", answer: "Maximum packing speed is 60 unit-dose pouches per minute; multi-dose runs average 55 pouches per minute." },
      { question: "Does every CAP(EX) include an MDU as well?", answer: "Yes. All three configurations include a 30-cell Manual Divide Unit alongside the three FSP units." },
      { question: "What pouch sizes and printing does it use?", answer: "Standard wrapping paper is 75 mm × 70 mm, with 55 mm × 50 mm available by order. Printing is thermal transfer with no limit on the number of characters or font size." },
      { question: "How do orders reach the machine?", answer: "Through an OCS (order communication system) linkage or by internal input on the 10.1-inch Windows 10 touch screen." },
      { question: "What is the power consumption?", answer: "200W typical, 600W maximum." },
    ],
    cta: {
      title: "Start at 52 cassettes. Extend when you need to.",
      description: "We'll map your formulary to a CAP(EX)-52FS, 72FS or 92FS — each with 3 FSP units standard — and show how the extension path fits your floor plan.",
    },
    relatedSlugs: ["wap-model", "ap-model", "mtc-model"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // WAP MODEL
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: "wap-model",
    manufacturer: "CRETEM",
    category: "Pouch packaging",
    name: "WAP Model",
    seriesName: "WAP-144FS · 184FS · 224FS",
    tagline: "Slim-Profile Intelligent Tablet Packing System",
    heroImage: `${IMG}/wap-224fs-01.webp`,
    heroImageAngled: `${IMG}/wap-224fs-02.webp`,
    heroCaption: "Pictured: WAP-224FS",
    description:
      "The WAP Model puts 144 to 224 cassettes into a cabinet only 460 mm deep. It stands against a wall like a cupboard yet runs the full CRETEM packing engine — infrared photodetection, 3 or 4 Free Shape Packing units, a 30- or 60-cell Manual Divide Unit and thermal-transfer printing at up to 60 unit-dose pouches per minute — on 300W typical power.",
    heroStats: [
      { value: "144–224", label: "Cassettes", note: "Three heights, one depth" },
      { value: "460 mm", label: "Cabinet depth", note: "1,252 mm wide" },
      { value: "60", label: "Pouches / min", note: "Max unit dose · avg 55 multi dose" },
      { value: "3–4", label: "FSP units", note: "30- or 60-cell MDU" },
    ],
    valueProps: [
      { title: "Automation for narrow rooms", description: "1,252 mm wide and 460 mm deep, the WAP fits along a wall where a full-depth cabinet cannot go. Capacity grows in height — 1,740, 1,900 or 2,060 mm — not depth." },
      { title: "More FSP capacity", description: "Specify 3 or 4 Free Shape Packing units so half tablets and irregular shapes run in parallel with cassette medications." },
      { title: "Lower power, lighter cabinet", description: "300W typical (700W max) and 250–350 kg depending on height, which simplifies installation in existing pharmacies." },
    ],
    howItWorks:
      "Staff replenish front-facing drug and FND cassettes through the T-slide system. Prescriptions arrive from an OCS linkage or internal input on the 10.1-inch touch panel. Infrared photodetection verifies each tablet. Three or four FSP units, with a dedicated FSP printer, pack irregular and half tablets; the MDU covers 30- or 60-cell manual-divide medications. The lower printing & packing system seals 75 mm × 70 mm pouches (55 mm × 50 mm by order) and finished pouches exit at the pouch outlet.",
    workflow: fsWorkflow,
    gallery: [
      platformImages.fspFront,
      platformImages.fspDetail,
      platformImages.mdu30,
      platformImages.cassetteReplenish,
      platformImages.cassetteDrawer,
      platformImages.lowerUnit,
    ],
    modules: [
      { name: "Free Shape Packing", abbreviation: "FSP", availability: "3 or 4 units", description: "Front-mounted FSP drawers with rotary hoppers and digital cell indicators pack free-shape and half tablets alongside cassette medications.", image: platformImages.fspDetailAlt },
      { name: "Manual Divide Unit", abbreviation: "MDU", availability: "30 or 60 cell", description: "Numbered cell tray for medications loaded by hand. Choose 30 or 60 cells to match how many non-cassette items you pack per run.", image: platformImages.mdu30 },
      { name: "T-slide cassette system", abbreviation: "T-slide", availability: "Standard", description: "Cassette drawers pull forward on the cabinet face so replenishment works in a wall-line installation.", image: platformImages.cassetteReplenishAlt },
    ],
    anatomy: [
      fsComponents.drugCassette,
      fsComponents.fndCassette,
      fsComponents.tSlide,
      { name: "Easy replenishment", description: "Front-facing cassettes are refilled from the cabinet face." },
      fsComponents.controlPanel,
      fsComponents.mdu,
      { name: "FSP printer", description: "Dedicated printer for pouches produced by the FSP units." },
      fsComponents.fsp,
      fsComponents.eStop,
      fsComponents.sound,
      fsComponents.printing,
      fsComponents.pouchOutlet,
    ],
    modelTable: {
      models: ["WAP-144FS", "WAP-184FS", "WAP-224FS"],
      rows: [
        { label: "No. of cassettes", values: ["144", "184", "224"] },
        { label: "Cassette types (S / M / L)", values: ["64 / 40 / 40", "104 / 40 / 40", "144 / 40 / 40"] },
        { label: "FSP", values: ["3 or 4", "3 or 4", "3 or 4"] },
        { label: "MDU", values: ["30 or 60 cell", "30 or 60 cell", "30 or 60 cell"] },
        { label: "Main body (W × D × H, mm)", values: ["1,252 × 460 × 1,740", "1,252 × 460 × 1,900", "1,252 × 460 × 2,060"] },
        { label: "Weight", values: ["250 kg", "300 kg", "350 kg"] },
      ],
    },
    specs: [
      { label: "No. of cassettes", value: "144 / 184 / 224 (by model)" },
      { label: "Means of control", value: 'Windows 10, touch screen 10.1"' },
      { label: "Refinement & detection", value: "Infrared photodetection" },
      { label: "Drug storage", value: "Cabinet type with cassettes installed in each single drawer" },
      { label: "Dispensing speed", value: "Max 60 unit-dose pouches/min · avg 55 multi-dose pouches/min" },
      { label: "Printing on the wrapper", value: "Thermal transfer — no limit to the number of characters or font size" },
      { label: "Wrapping paper size", value: "75 mm × 70 mm, or 55 mm × 50 mm by order" },
      { label: "Input", value: "OCS linkage or internal input" },
      { label: "FSP", value: "3 or 4" },
      { label: "MDU", value: "30 cell or 60 cell" },
      { label: "Main body (W × D × H)", value: "1,252 × 460 × 1,740 / 1,900 / 2,060 mm" },
      { label: "Weight", value: "250 / 300 / 350 kg" },
      { label: "Power consumption", value: "300W (max 700W)" },
      { label: "Power supply", value: POWER_SUPPLY },
    ],
    highlights: [
      { title: "460 mm slim depth", description: "1,252 mm wide and only 460 mm deep, the WAP stands against a wall like a cabinet." },
      { title: "144 to 224 cassettes", description: "WAP-144FS, WAP-184FS and WAP-224FS grow in height, not depth." },
      { title: "3 or 4 FSP units", description: "More Free Shape Packing capacity for half tablets and irregular shapes." },
      { title: "60 pouches per minute", description: "Max 60 unit-dose pouches per minute; average 55 on multi-dose runs." },
      { title: "300W typical power", description: "300W typical and 700W maximum." },
      { title: "T-slide replenishment", description: "Front-facing cassettes keep restocking on the cabinet face." },
      { title: "30- or 60-cell MDU", description: "Specify the Manual Divide Unit size that fits your non-cassette volume." },
      { title: "250–350 kg", description: "Lighter cabinet by height — 250, 300 or 350 kg." },
    ],
    features: [
      "Slim 460 mm cabinet depth for wall-line installation",
      "144, 184 or 224 cassettes in small, medium and large sizes",
      "T-slide cassette system with easy front replenishment",
      'Windows 10 control with 10.1" touch screen',
      "Infrared photodetection on every dispensed tablet",
      "3 or 4 Free Shape Packing units with dedicated FSP printer",
      "30-cell or 60-cell Manual Divide Unit",
      "300W typical power consumption (max 700W)",
    ],
    integration: fsIntegration,
    useCases: ["Retail pharmacies with limited floor space", "Hospital satellite pharmacies", "Wall-line packaging rooms"],
    faqs: [
      { question: "Why choose the WAP Model instead of the AP Model?", answer: "Choose WAP when floor depth is the constraint. It is only 460 mm deep and 1,252 mm wide, with 144–224 cassettes and 3 or 4 FSP units. The AP Model is a deeper 1,030 mm cabinet with 207–500 cassettes and 1 or 2 FSP units. Packing speed and pouch options are the same." },
      { question: "How many cassettes does each WAP size hold?", answer: "WAP-144FS holds 144 cassettes (64 small, 40 medium, 40 large). WAP-184FS holds 184 (104 / 40 / 40). WAP-224FS holds 224 (144 / 40 / 40). Width and depth stay 1,252 × 460 mm; height grows from 1,740 mm to 2,060 mm." },
      { question: "How fast does the WAP pack?", answer: "Maximum 60 unit-dose pouches per minute; multi-dose runs average 55 pouches per minute on all three sizes." },
      { question: "How many FSP units can I specify?", answer: "Every WAP configuration can be specified with 3 or 4 Free Shape Packing units." },
      { question: "What MDU sizes are available?", answer: "A 30-cell or 60-cell Manual Divide Unit." },
      { question: "What are the power requirements?", answer: "300W typical (700W maximum). Supported supplies are 220V/60Hz (Korea), 120V/60Hz (US) and 230–240V/50Hz (Europe)." },
      { question: "What pouch sizes are available?", answer: "Standard wrapping paper is 75 mm × 70 mm. A 55 mm × 50 mm size is available by order." },
    ],
    cta: {
      title: "Fit cassette packing into a 460 mm-deep wall line",
      description: "See how the WAP Model stands against a wall, restocks from the front and still packs 60 pouches per minute. We'll size 144, 184 or 224 cassettes to your floor plan.",
    },
    relatedSlugs: ["ap-model", "cap-ex-model", "ap-md-model"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AP MODEL
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: "ap-model",
    manufacturer: "CRETEM",
    category: "Pouch packaging",
    name: "AP Model",
    seriesName: "AP-207FS · 267FS · 336FS · 405FS · 500FS",
    tagline: "Intelligent Tablet Packing System",
    heroImage: `${IMG}/ap-405fs-01.webp`,
    heroImageAngled: `${IMG}/ap-405fs-02.webp`,
    heroCaption: "Pictured: AP-405FS",
    description:
      "The AP Model is CRETEM's core floor-standing packager. Five configurations from 207 to 500 cassettes share the same T-slide cassette system, infrared photodetection and thermal-transfer pouch printing at up to 60 unit-dose pouches per minute. The series includes auto-repack for error pouches, sound alarm messages and a stock management system for controlling drugs. MDU together with 2 FSP units help the pharmacy pack frequently changing drug shapes.",
    heroStats: [
      { value: "207–500", label: "Cassettes", note: "Five configurations" },
      { value: "60", label: "Pouches / min", note: "Max unit dose · avg 55 multi dose" },
      { value: "1–2", label: "FSP units", note: "On every model" },
      { value: "30 / 60", label: "MDU cells", note: "Manual Divide Unit" },
    ],
    valueProps: [
      { title: "Auto-repack for error pouches", description: "The AP series includes auto-repack for error pouches, so pouches flagged in error can be packed again without restarting the run." },
      { title: "Sound alarm messages", description: "Sound alarm messages alert staff to operating status so the packing line can be monitored without watching the screen." },
      { title: "Stock management for controlling drugs", description: "A stock management system helps pharmacies control the drugs held in the packager." },
      { title: "MDU and 2 FSP for changing drug shapes", description: "The Manual Divide Unit together with 2 Free Shape Packing units help the pharmacy pack frequently changing drug shapes. Every AP size can be specified with 1 or 2 FSP units and a 30- or 60-cell MDU." },
    ],
    howItWorks:
      "Technicians replenish small, medium and large drug cassettes through the T-slide system. Prescriptions arrive from an OCS linkage or internal input on the 10.1-inch Windows 10 touch panel. Infrared photodetection verifies each tablet as it is dispensed. FSP units pack free-shape and half tablets; the MDU covers manual-divide medications — together, MDU and 2 FSP units help pack frequently changing drug shapes. Error pouches can be auto-repacked. Sound alarm messages and the stock management system support day-to-day control of the line. The printing & packing system seals 75 mm × 70 mm pouches (55 mm × 50 mm by order) with thermal-transfer text that has no character or font-size limit; finished pouches exit at the pouch outlet.",
    workflow: fsWorkflow,
    gallery: [
      platformImages.cassetteDrawer,
      platformImages.cassetteReplenish,
      platformImages.fspDetailAlt,
      platformImages.mdu30,
      platformImages.lowerUnit,
      platformImages.cassetteReplenishAlt,
    ],
    modules: [
      { name: "Free Shape Packing", abbreviation: "FSP", availability: "1 or 2 units", description: "Rotary FSP hoppers with a dedicated FSP printer pack half tablets and irregular shapes that do not fit a standard cassette. Specified as 2 FSP units with the MDU, they help the pharmacy pack frequently changing drug shapes.", image: platformImages.fspDetail },
      { name: "Manual Divide Unit", abbreviation: "MDU", availability: "30 or 60 cell", description: "Numbered cell tray for medications loaded by hand. Together with 2 FSP units, the MDU helps pack frequently changing drug shapes so non-cassette items still follow the same pouch sequence.", image: platformImages.mdu30 },
      { name: "T-slide cassette system", abbreviation: "T-slide", availability: "Standard", description: "Drawers of small, medium and large cassettes slide forward for cleaning and refilling from the front.", image: platformImages.cassetteReplenish },
    ],
    anatomy: [
      fsComponents.drugCassette,
      fsComponents.fndCassette,
      fsComponents.tSlide,
      { name: "Easy replenishment", description: "Cassettes are refilled from the cabinet face via the T-slide drawers." },
      fsComponents.controlPanel,
      fsComponents.mdu,
      { name: "FSP printer", description: "Dedicated printer for pouches produced by the FSP units." },
      { name: "FSP — Free Shape Packing unit", description: "Packs free-shape and half tablets that do not fit a standard cassette. 1 or 2 units; 2 FSP with the MDU help pack frequently changing drug shapes." },
      fsComponents.eStop,
      { name: "Sound alarm message", description: "Sound alarm messages during operation so staff can hear status and alerts without watching the screen." },
      { name: "Auto-repack", description: "Auto-repack for error pouches so pouches flagged in error can be packed again." },
      { name: "Stock management system", description: "Helps the pharmacy control drugs held in the packager." },
      fsComponents.printing,
      fsComponents.pouchOutlet,
    ],
    modelTable: {
      models: ["AP-207FS", "AP-267FS", "AP-336FS", "AP-405FS", "AP-500FS"],
      rows: [
        { label: "No. of cassettes", values: ["207", "267", "336", "405", "500"] },
        { label: "Cassette types (S / M / L)", values: ["69 / 69 / 69", "129 / 69 / 69", "198 / 69 / 69", "267 / 69 / 69", "316 / 92 / 92"] },
        { label: "FSP", values: ["1 or 2", "1 or 2", "1 or 2", "1 or 2", "1 or 2"] },
        { label: "MDU", values: ["30 or 60 cell", "30 or 60 cell", "30 or 60 cell", "30 or 60 cell", "30 or 60 cell"] },
        { label: "Main body (W × D × H, mm)", values: ["840 × 1,030 × 1,700", "840 × 1,030 × 1,700", "840 × 1,030 × 1,846", "840 × 1,030 × 2,100", "1,100 × 1,030 × 2,100"] },
        { label: "Weight", values: ["520 kg", "540 kg", "580 kg", "620 kg", "800 kg"] },
      ],
    },
    specs: [
      { label: "No. of cassettes", value: "207 / 267 / 336 / 405 / 500 (by model)" },
      { label: "Means of control", value: 'Windows 10, touch screen 10.1"' },
      { label: "Refinement & detection", value: "Infrared photodetection" },
      { label: "Drug storage", value: "Cabinet type with cassettes installed in each single drawer" },
      { label: "Dispensing speed", value: "Max 60 unit-dose pouches/min · avg 55 multi-dose pouches/min" },
      { label: "Printing on the wrapper", value: "Thermal transfer — no limit to the number of characters or font size" },
      { label: "Wrapping paper size", value: "75 mm × 70 mm, or 55 mm × 50 mm by order" },
      { label: "Input", value: "OCS linkage or internal input" },
      { label: "FSP", value: "1 or 2" },
      { label: "MDU", value: "30 cell or 60 cell" },
      { label: "Main body (W × D × H)", value: "840 × 1,030 × 1,700–2,100 mm · AP-500FS: 1,100 × 1,030 × 2,100 mm" },
      { label: "Weight", value: "520 / 540 / 580 / 620 / 800 kg" },
      { label: "Power consumption", value: "500W (max 1000W)" },
      { label: "Power supply", value: POWER_SUPPLY },
    ],
    highlights: [
      { title: "Auto-repack for error pouches", description: "Error pouches can be auto-repacked without restarting the run." },
      { title: "Sound alarm messages", description: "Audio alarms and status messages during operation." },
      { title: "Stock management system", description: "Helps pharmacies control the drugs held in the packager." },
      { title: "MDU + 2 FSP", description: "The Manual Divide Unit and 2 Free Shape Packing units help pack frequently changing drug shapes." },
      { title: "T-slide cassette system", description: "Built for easy replenishment — restock cassettes from the front of the cabinet." },
      { title: "Five capacity steps", description: "207, 267, 336, 405 or 500 cassettes to match formulary size." },
      { title: "60 pouches per minute", description: "Max 60 unit-dose pouches per minute; average 55 on multi-dose runs." },
      { title: "Infrared photodetection", description: "Optical verification of each tablet across the full cassette mix." },
    ],
    features: [
      "Auto-repack for error pouches",
      "Sound alarm messages during operation",
      "Stock management system for controlling drugs",
      "MDU and 2 FSP help pack frequently changing drug shapes",
      "T-slide cassette system designed for easy replenishment",
      "207 to 500 cassettes in small, medium and large sizes",
      "1 or 2 Free Shape Packing units with dedicated FSP printer",
      "30-cell or 60-cell Manual Divide Unit",
    ],
    integration: fsIntegration,
    useCases: ["Hospital pharmacies", "Central fill", "Retail multi-dose programs"],
    faqs: [
      { question: "Does the AP series auto-repack error pouches?", answer: "Yes. The AP series includes auto-repack for error pouches, so pouches flagged in error can be packed again without restarting the run." },
      { question: "What is the sound alarm message?", answer: "Sound alarm messages play during operation so staff can hear status and alerts without watching the screen." },
      { question: "Does the AP Model include a stock management system?", answer: "Yes. A stock management system helps pharmacies control the drugs held in the packager." },
      { question: "How do MDU and FSP handle frequently changing drug shapes?", answer: "The Manual Divide Unit together with 2 Free Shape Packing units help the pharmacy pack frequently changing drug shapes. All five AP configurations can be specified with 1 or 2 FSP units and either a 30-cell or 60-cell MDU." },
      { question: "Which AP Model capacity should I choose?", answer: "Choose by active formulary size: AP-207FS (207 cassettes), AP-267FS (267), AP-336FS (336), AP-405FS (405) or AP-500FS (500). The first four share an 840 × 1,030 mm footprint and grow in height; the AP-500FS widens to 1,100 mm to hold the larger cassette mix." },
      { question: "What is the T-slide system?", answer: "T-slide is the cassette drawer design in the AP cabinet. Drawers slide forward so technicians can restock medications from the front of the machine instead of removing entire drawer stacks." },
      { question: "How fast does the AP Model pack?", answer: "Maximum 60 unit-dose pouches per minute; multi-dose runs average 55 pouches per minute across all five models." },
      { question: "How does the AP Model differ from the AP MD Model?", answer: "The AP Model uses a 10.1-inch touch screen, a T-slide cassette layout and FSP/MDU options on every size from 207 to 500 cassettes. The AP MD Model is the higher-capacity multi-dose cabinet with a 17-inch screen, individual drawer locks and A/B configurations up to 480 cassettes, where FSP and a 60-cell MDU are B-series options." },
      { question: "What are the power requirements?", answer: "500W typical (1000W maximum). Supported supplies are 220V/60Hz (Korea), 120V/60Hz (US) and 230–240V/50Hz (Europe)." },
    ],
    cta: {
      title: "Match an AP Model to your cassette count",
      description: "We'll walk through auto-repack, stock management, sound alarm messages, and whether MDU with 2 FSP units fits the drug shapes you pack.",
    },
    relatedSlugs: ["ap-md-model", "wap-model", "cap-ex-model"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AP MD MODEL
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: "ap-md-model",
    manufacturer: "CRETEM",
    category: "Pouch packaging",
    name: "AP MD Model",
    seriesName: "AP-300MD · 360MD · 480MD (A / B)",
    tagline: "High-Capacity Multi-Dose Packaging System",
    heroImage: `${IMG}/ap-md-model.webp`,
    heroImageFit: "cover",
    heroCaption: "AP MD Model — from CRETEM product documentation",
    description:
      "The AP MD Model is CRETEM's high-capacity multi-dose cabinet. Choose 300, 360 or 480 cassettes, each in an A configuration (cassette-only) or a B configuration that adds Free Shape Packing and a 60-cell Manual Divide Unit. The series includes auto-repack for error pouches, sound alarm messages and a stock management system for controlling drugs. MDU together with 2 FSP units help the pharmacy pack frequently changing drug shapes. A 17-inch Windows 10 touch panel runs the line, individual drawer locks secure the cassettes, and infrared photodetection verifies every tablet.",
    heroStats: [
      { value: "300–480", label: "Cassettes", note: "Three capacities" },
      { value: "60", label: "Pouches / min", note: "Max unit dose · avg 55 multi dose" },
      { value: '17"', label: "Touch screen", note: "Windows 10 IPC" },
      { value: "A / B", label: "Configurations", note: "B adds FSP + 60 MDU" },
    ],
    valueProps: [
      { title: "Auto-repack for error pouches", description: "The AP MD series includes auto-repack for error pouches, so pouches flagged in error can be packed again without restarting the run." },
      { title: "Sound alarm messages", description: "Sound alarm messages alert staff to operating status so the packing line can be monitored without watching the screen." },
      { title: "Stock management for controlling drugs", description: "A stock management system helps pharmacies control the drugs held in the packager." },
      { title: "MDU and 2 FSP for changing drug shapes", description: "The Manual Divide Unit together with 2 Free Shape Packing units help the pharmacy pack frequently changing drug shapes. On AP MD, FSP and a 60-cell MDU are fitted on B-series configurations." },
    ],
    howItWorks:
      "Pharmacy staff load medications into locked single-drawer drug cassettes sized small, medium or large. Prescriptions arrive through an OCS link or are entered on the 17-inch touch screen. Infrared photodetection verifies each tablet as it is dispensed. FSP and the MDU handle free-shape tablets and manually divided medications — together, MDU and 2 FSP units help pack frequently changing drug shapes. Error pouches can be auto-repacked. Sound alarm messages and the stock management system support day-to-day control of the line. The printing & packing system applies thermal-transfer text with no character or font-size limit onto 75 mm × 70 mm pouches. Finished pouches exit through the pouch outlet.",
    workflow: [
      { title: "Order received", description: "Prescriptions arrive through the OCS linkage or are entered on the 17-inch Windows 10 touch screen." },
      { title: "Cassettes dispense", description: "Tablets are dispensed from locked single-drawer cassettes and verified by infrared photodetection." },
      { title: "FSP and MDU (B-series)", description: "FSP and a 60-cell MDU handle free-shape tablets and manually divided medications, helping the pharmacy pack frequently changing drug shapes." },
      { title: "Pouch is printed and sealed", description: "Thermal-transfer printing on 75 mm × 70 mm wrapping paper, with no character or font-size limit." },
      { title: "Pouches exit", description: "Finished pouches leave through the pouch outlet; a medicine collection box sits above the lower cabinet." },
    ],
    gallery: [
      platformImages.cassetteDrawer,
      platformImages.lowerUnit,
      platformImages.fspDetail,
    ],
    galleryNote: "Component photography shows CRETEM platform modules shared across the range.",
    modules: [
      { name: "Free Shape Packing", abbreviation: "FSP", availability: "B-series: 1 unit", description: "Handles half tablets, irregular shapes and medications that do not have a dedicated cassette. Specified with the 60-cell MDU, FSP helps the pharmacy pack frequently changing drug shapes. Fitted on AP-300MD-B, 360MD-B and 480MD-B.", image: platformImages.fspDetail },
      { name: "Manual Divide Unit", abbreviation: "MDU", availability: "B-series: 60 cell", description: "60-cell tray for medications added by hand. Together with FSP, the MDU helps pack frequently changing drug shapes so non-cassette items still follow the same pouch sequence.", image: platformImages.mdu30 },
    ],
    anatomy: [
      fsComponents.drugCassette,
      { name: "Individual drawer lock", description: "Each cassette drawer locks independently." },
      { name: "Control panel", description: 'Industrial PC with a 17-inch Windows 10 touch screen on a swivel arm.' },
      { name: "Sound alarm message", description: "Sound alarm messages during operation so staff can hear status and alerts without watching the screen." },
      { name: "FSP — Free Shape Packing", description: "Option depending on the installation (B-series). Together with the MDU, helps pack frequently changing drug shapes." },
      { name: "MDU — Manual Divide Unit", description: "Option depending on the installation (B-series, 60 cell). Together with FSP, helps pack frequently changing drug shapes." },
      { name: "Auto-repack", description: "Auto-repack for error pouches so pouches flagged in error can be packed again." },
      { name: "Stock management system", description: "Helps the pharmacy control drugs held in the packager." },
      { name: "Medicine collection box", description: "Collection box on the front of the mid cabinet." },
      fsComponents.eStop,
      fsComponents.printing,
      fsComponents.pouchOutlet,
    ],
    modelTable: {
      models: ["AP-300MD-A", "AP-300MD-B", "AP-360MD-A", "AP-360MD-B", "AP-480MD-A", "AP-480MD-B"],
      rows: [
        { label: "No. of cassettes", values: ["300", "300", "360", "360", "480", "480"] },
        { label: "Cassette types (S / M / L)", values: ["132 / 120 / 48", "132 / 120 / 48", "156 / 144 / 60", "156 / 144 / 60", "208 / 192 / 80", "208 / 192 / 80"] },
        { label: "FSP", values: ["No FSP", "1 FSP", "No FSP", "1 FSP", "No FSP", "1 FSP"] },
        { label: "MDU", values: ["No MDU", "60 MDU", "No MDU", "60 MDU", "No MDU", "60 MDU"] },
        { label: "Main body (W × D × H, mm)", values: ["896 × 1,070 × 2,021", "896 × 1,070 × 1,907", "896 × 1,070 × 2,021", "896 × 1,070 × 1,907", "1,174 × 1,070 × 2,141", "1,174 × 1,070 × 2,027"] },
        { label: "Weight", values: ["650 kg", "670 kg", "650 kg", "670 kg", "800 kg", "820 kg"] },
      ],
    },
    specs: [
      { label: "No. of cassettes", value: "300 / 360 / 480 (by model)" },
      { label: "Means of control", value: 'Windows 10, touch screen 17"' },
      { label: "Refinement & detection", value: "Infrared photodetection" },
      { label: "Drug storage", value: "Cabinet type with cassettes installed in each single drawer" },
      { label: "Dispensing speed", value: "Max 60 unit-dose pouches/min · avg 55 multi-dose pouches/min" },
      { label: "Printing on the wrapper", value: "Thermal transfer — no limit to the number of characters or font size" },
      { label: "Wrapping paper size", value: "75 mm × 70 mm" },
      { label: "Input", value: "OCS linkage or internal input" },
      { label: "FSP", value: "None (A) · 1 FSP (B)" },
      { label: "MDU", value: "None (A) · 60 MDU (B)" },
      { label: "Main body (W × D × H)", value: "896 × 1,070 × 1,907–2,021 mm · AP-480MD: 1,174 × 1,070 × 2,027–2,141 mm" },
      { label: "Weight", value: "650 / 670 / 650 / 670 / 800 / 820 kg" },
      { label: "Power consumption", value: "500W (max 1000W)" },
      { label: "Power supply", value: POWER_SUPPLY },
    ],
    highlights: [
      { title: "Auto-repack for error pouches", description: "Error pouches can be auto-repacked without restarting the run." },
      { title: "Sound alarm messages", description: "Audio alarms and status messages during operation." },
      { title: "Stock management system", description: "Helps pharmacies control the drugs held in the packager." },
      { title: "MDU + 2 FSP", description: "The Manual Divide Unit and 2 Free Shape Packing units help pack frequently changing drug shapes." },
      { title: "Up to 480 cassettes", description: "Three cabinet sizes — 300, 360 or 480 cassettes." },
      { title: "60 unit-dose pouches / min", description: "Maximum 60 unit-dose pouches per minute; average 55 on multi-dose runs." },
      { title: "17-inch touch control", description: "Windows 10 industrial PC with a 17-inch touch screen." },
      { title: "Individual drawer locks", description: "Each cassette drawer locks independently." },
    ],
    features: [
      "Auto-repack for error pouches",
      "Sound alarm messages during operation",
      "Stock management system for controlling drugs",
      "MDU and 2 FSP help pack frequently changing drug shapes",
      "300, 360 or 480 dedicated cassettes in small, medium and large sizes",
      "Cabinet-type storage with cassettes in single drawers and individual locks",
      "Optional Free Shape Packing for irregular and half tablets (B-series)",
      "Optional 60-cell Manual Divide Unit (B-series)",
    ],
    integration: fsIntegration,
    useCases: ["Hospital pharmacies", "Long-term care central fill", "High-volume multi-dose programs"],
    faqs: [
      { question: "Does the AP MD series auto-repack error pouches?", answer: "Yes. The AP MD series includes auto-repack for error pouches, so pouches flagged in error can be packed again without restarting the run." },
      { question: "What is the sound alarm message?", answer: "Sound alarm messages play during operation so staff can hear status and alerts without watching the screen." },
      { question: "Does the AP MD Model include a stock management system?", answer: "Yes. A stock management system helps pharmacies control the drugs held in the packager." },
      { question: "How do MDU and FSP handle frequently changing drug shapes?", answer: "The Manual Divide Unit together with 2 Free Shape Packing units help the pharmacy pack frequently changing drug shapes. On AP MD, FSP and a 60-cell MDU are fitted on B-series configurations (AP-300MD-B, 360MD-B and 480MD-B)." },
      { question: "What is the difference between A-series and B-series AP MD units?", answer: "A-series units are cassette-only. B-series units add Free Shape Packing (FSP) and a 60-cell Manual Divide Unit (MDU) so the same cabinet can pack cassette medications plus half tablets, irregular shapes and drugs that are not assigned to a cassette." },
      { question: "How many cassettes can I specify?", answer: "AP-300MD (300 cassettes: 132 small, 120 medium, 48 large), AP-360MD (360: 156 / 144 / 60) and AP-480MD (480: 208 / 192 / 80). Each capacity is offered in both A and B configurations." },
      { question: "How fast does the AP MD pack?", answer: "Maximum 60 unit-dose pouches per minute. Multi-dose runs average 55 pouches per minute." },
      { question: "What are the power requirements?", answer: "500W typical (1000W maximum). Power supply options are 220V/60Hz (Korea), 120V/60Hz (US) and 230–240V/50Hz (Europe)." },
    ],
    cta: {
      title: "Size the AP MD to your formulary",
      description: "We'll walk through auto-repack, stock management, sound alarm messages, and whether B-series FSP and 60-cell MDU fit the drug shapes you pack.",
    },
    relatedSlugs: ["ap-model", "wap-model", "cap-ex-model"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MTC MODEL
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: "mtc-model",
    manufacturer: "CRETEM",
    category: "Vial packaging",
    name: "MTC Model",
    seriesName: "MTC-30 Multi Tablet Counter",
    tagline: "Semi-Automatic Vial Packaging · Multi Tablet Counter",
    heroImage: `${IMG}/mtc-30.webp`,
    heroCaption: "MTC-30 with optional touch panel — components labelled",
    demoAvailable: true,
    description:
      "The CRETEM MTC-30 counts multiple prescriptions into cups or bottles at the same time. Thirty canisters dispense at up to 290 pills per minute — 5 medications × 90 fills (450 pills) in about 2.25 minutes — and the unit extends to 90 canisters with two extender units, all under one software instance. Orders arrive from your OCS, HIS or PMS, and each completed bottle label is barcode-verified on the touch panel. A demonstration video is available.",
    heroStats: [
      { value: "30 → 90", label: "Canisters", note: "Two extender units" },
      { value: "290", label: "Pills / min", note: "Maximum dispensing speed" },
      { value: "≈30 s", label: "Fast dispensing", note: "Per order" },
      { value: "180 mm", label: "Depth", note: "808 mm wide · 1,220 mm high" },
    ],
    valueProps: [
      { title: "Count many prescriptions at once", description: "The MTC starts multiple orders simultaneously — direct drop into cup or the user's bottle — so the vial line is not serialised one script at a time." },
      { title: "Grows to 90 canisters", description: "Standard 30 canisters extend to 60 or 90 with two more extender units. One software instance controls all connected units." },
      { title: "Fits the existing bench", description: "Each unit is 808 mm wide and only 180 mm deep, sized for table-top or wall-line installation." },
    ],
    howItWorks:
      "Prescription orders are received from OCS, HIS or PMS. The operator places a cup into position and sends the order to the MTC. The MTC starts multiple orders at the same time and 'Dispensing' is shown on the touch panel. Labels print as each order is processed. When orders complete, 'Wait Bottle Out' appears; the operator removes each cup and fills each bottle. Order status changes to 'Checked By' — the user confirms and attaches the label to each bottle, then scans the completed bottle label barcode for verification.",
    workflow: [
      { title: "Order received", description: "Prescription (order) received from OCS, HIS or PMS." },
      { title: "Cup in position", description: "Place the cup into position and send the order to the MTC." },
      { title: "Multiple orders dispense", description: "MTC starts multiple orders at the same time; 'Dispensing' is displayed on the touch panel." },
      { title: "Labels print", description: "Labels are printed for each order in process." },
      { title: "Bottle out", description: "'Wait Bottle Out' is displayed when the order is completed; each cup is taken out and each bottle filled." },
      { title: "Check and label", description: "Status changes to 'Checked By'; the user confirms and attaches the label to each bottle." },
      { title: "Barcode verification", description: "Scan the completed bottle label (order number) for verification on the touch panel." },
    ],
    gallery: [
      platformImages.canisters,
    ],
    modules: [
      { name: "Touch panel", abbreviation: "Optional", availability: "Optional device, not included", description: "Recommended: Microsoft Surface Go 2 LTE or higher — 10.5-inch display, Windows 10 Professional, USB to RS232C communication.", image: { src: `${IMG}/mtc-30.webp`, alt: "MTC-30 with optional touch panel on an articulated arm", fit: "contain" } },
      { name: "Barcode scanner", abbreviation: "Optional", availability: "Recommended peripheral", description: "Recommended: ZEBRA SYMBOL-DS2208 — 1D/2D and PDF417, PS/2, USB or RS232C interface, 0–38.6 cm reading distance.", image: { src: `${IMG}/mtc-barcode-scanner.png`, alt: "Handheld barcode scanner used to verify completed MTC-30 bottle labels", fit: "contain" } },
      { name: "Label printer", abbreviation: "Optional", availability: "Recommended peripheral", description: "Recommended: ZEBRA GK420E — direct thermal, 203 dpi, USB / RS-232C / Ethernet, max 152 mm/s print speed, 19–108 mm label width.", image: { src: `${IMG}/mtc-label-printer.png`, alt: "Desktop thermal label printer for MTC-30 bottle labels", fit: "contain" } },
    ],
    anatomy: [
      { name: "Canister", description: "Dedicated canister per medication, 30 per unit." },
      { name: "FND canister base", description: "Base plate that seats each canister." },
      { name: "Cup", description: "Collection cup below each canister for direct drop dispensing." },
      { name: "Touch panel & arm", description: "Optional Windows 10 touch panel on an articulated arm (not included)." },
      { name: "Bottle position", description: "Direct drop into the user's bottle (bottle not included)." },
      { name: "Power button", description: "Front-panel power control." },
    ],
    modelTable: {
      models: ["MTC-30", "MTC-30 + 1 extender", "MTC-30 + 2 extenders"],
      rows: [
        { label: "Canisters", values: ["30", "60", "90"] },
        { label: "Control", values: ["One software instance", "One software instance", "One software instance"] },
        { label: "Main body per unit (W × D × H, mm)", values: ["808 × 180 × 1,220", "808 × 180 × 1,220", "808 × 180 × 1,220"] },
        { label: "Weight per unit", values: ["60 kg", "60 kg", "60 kg"] },
      ],
    },
    specs: [
      { label: "Product name", value: "CRETEM MTC-30 (Multi Tablet Counter)" },
      { label: "Cassette quantity", value: "30 cassettes — extendable to max 90 with two more extender units" },
      { label: "Product control", value: "Microsoft Surface Go or touch panel (Windows 10), optional device" },
      { label: "Communication method", value: "RS422" },
      { label: "Medication detection", value: "Infrared photodetection" },
      { label: "Medication storage", value: "Cabinet type with cassettes" },
      { label: "Dispensing speed", value: "Max 290 pills/min · 5 medicines × 90 fills (450 pills) in 2.25 min" },
      { label: "Packing", value: "Direct drop into cup or user's bottle" },
      { label: "Dimension (W × D × H)", value: '808 × 180 × 1,220 mm (31.8" × 7.1" × 48") per unit' },
      { label: "Weight", value: "60 kg (132 lb)" },
      { label: "Power consumption", value: "100W (max 500W)" },
      { label: "Power supply", value: POWER_SUPPLY },
    ],
    highlights: [
      { title: "290 pills per minute", description: "Maximum dispensing speed across simultaneous orders." },
      { title: "Multi-counter bottle packing", description: "Counts medications for multiple prescriptions at the same time." },
      { title: "Fast dispensing within 30 seconds", description: "Complete order dispensing within about 30 seconds." },
      { title: "Extendable to 90 canisters", description: "Add two extender units; one software instance controls all." },
      { title: "Infrared photodetection", description: "Every tablet is counted optically." },
      { title: "OCS / HIS / PMS orders", description: "Receives prescriptions from order communication, hospital information or pharmacy management systems." },
      { title: "Compact table-top size", description: "808 × 180 × 1,220 mm per unit." },
      { title: "Barcode verification", description: "Completed bottle labels are scanned for order verification." },
    ],
    features: [
      "Multi-counter for bottle packing of medications at the same time",
      "Control of 30 canisters, extendable to max 90 canisters",
      "Compact size for table-top installation",
      "Fast dispensing within 30 seconds",
      "Infrared photodetection",
      "Direct drop into cup or user's bottle",
      "RS422 communication",
      "Label printing and barcode verification per order",
      "Demo video available",
    ],
    integration: ["OCS (Order Communication System)", "HIS (Hospital Information System)", "PMS (Pharmacy Management System)"],
    useCases: ["Retail pharmacies", "Outpatient pharmacies", "Hospital pharmacies"],
    faqs: [
      { question: "Is there a demo video of the MTC-30?", answer: "Yes. A demonstration video of the MTC-30 is available. Request a viewing with our team and we'll walk through simultaneous vial filling and the 30 → 60 → 90 canister extension path." },
      { question: "How many canisters does the MTC-30 support?", answer: "The MTC-30 comes standard with 30 canisters and can be extended to a maximum of 90 with two more extender units, all controlled by a single software instance." },
      { question: "How fast does the MTC-30 dispense?", answer: "Maximum dispensing speed is 290 pills per minute. Five kinds of medicine at 90 fills each (450 pills total) take about 2.25 minutes." },
      { question: "What systems does the MTC-30 receive orders from?", answer: "OCS (Order Communication System), HIS (Hospital Information System) or PMS (Pharmacy Management System). The unit communicates over RS422." },
      { question: "What control interface does it use?", answer: "An optional touch panel — recommended Microsoft Surface Go 2 LTE or higher running Windows 10 Professional, connected via USB to RS232C." },
      { question: "Which barcode scanner and label printer are recommended?", answer: "ZEBRA SYMBOL-DS2208 scanner (1D/2D, PDF417) and ZEBRA GK420E label printer (203 dpi, USB / RS-232C / Ethernet)." },
      { question: "What are the power requirements?", answer: "100W typical (500W maximum), on 220V/60Hz (Korea), 120V/60Hz (US) or 230–240V/50Hz (Europe)." },
    ],
    cta: {
      title: "Watch the MTC-30 demo",
      description: "A demonstration video of the MTC-30 is available. Request a viewing and we'll walk through simultaneous vial filling and the 30 → 60 → 90 canister extension path.",
    },
    relatedSlugs: ["tablet-counter", "cap-ex-model", "wap-model"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TABLET COUNTER
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: "tablet-counter",
    manufacturer: "CRETEM",
    category: "Tablet counting",
    name: "Tablet Counter",
    tagline: "Compact Infrared Tablet Counting Station",
    heroImage: `${IMG}/tablet-counter.webp`,
    heroImageFit: "cover",
    description:
      "The CRETEM Tablet Counter is a compact benchtop station for fast, accurate counting of oral solid medications. Infrared photodetection registers every tablet at up to 280 per minute, counted tablets drop into a transparent collection bin, and the whole unit measures 130 × 175 × 230 mm and draws just 4.5W.",
    heroStats: [
      { value: "280", label: "Tablets / min", note: "Maximum speed" },
      { value: "IR", label: "Photodetection", note: "Tablet-by-tablet" },
      { value: "130 mm", label: "Wide", note: "175 mm deep · 230 mm high" },
      { value: "4.5W", label: "Power", note: "AC 110–220V, 50/60Hz" },
    ],
    valueProps: [
      { title: "Faster than tray counting", description: "Up to 280 tablets per minute with optical verification of each tablet, so staff move from bottle to vial without manual recounts." },
      { title: "Fits any counter", description: "At 130 × 175 × 230 mm and 10 kg, it sits beside a vial-filling station — no floor space or dedicated room." },
      { title: "Simple keypad workflow", description: "Numeric keypad with List, ALL, Start and Stop keys and a two-line display keep training short." },
    ],
    howItWorks:
      "Pharmacy staff place tablets into the unit and enter the target quantity on the numeric keypad, or select a full-count cycle. Infrared photodetection tracks each tablet as it passes through the counting path. Counted tablets drop into the transparent collection bin at the front of the station. The display confirms the running count so the next batch can start immediately.",
    workflow: [
      { title: "Load tablets", description: "Place tablets into the unit's top hopper." },
      { title: "Set the count", description: "Enter a target quantity on the numeric keypad, or choose ALL for a full-bottle count." },
      { title: "Start", description: "Infrared photodetection registers each tablet as it passes the counting path — up to 280 per minute." },
      { title: "Collect", description: "Counted tablets drop into the transparent front bin; the display shows the running count." },
    ],
    anatomy: [
      { name: "Numeric keypad", description: "0–9 keys with CLR and DEL, plus List, ALL, Start and Stop function keys." },
      { name: "Two-line display", description: "Shows the target and running count." },
      { name: "READY indicator", description: "Status key/indicator on the control panel." },
      { name: "Infrared counting path", description: "Photodetection sensors register each tablet." },
      { name: "Transparent collection bin", description: "Removable front bin with handle for lifting the counted batch into a vial." },
    ],
    specs: [
      { label: "Refinement & detection", value: "Infrared photodetection" },
      { label: "Speed", value: "Max 280 per min" },
      { label: "Size of the main body (W × D × H)", value: "130 × 175 × 230 mm" },
      { label: "Weight of the main body", value: "10 kg" },
      { label: "Power consumption", value: "4.5W" },
      { label: "Power supply", value: "AC 110–220V, 50/60Hz" },
    ],
    highlights: [
      { title: "280 tablets per minute", description: "Maximum counting speed for retail fill lines and batch work." },
      { title: "Infrared photodetection", description: "Each tablet is verified optically as it is counted." },
      { title: "Countertop compact", description: "130 × 175 × 230 mm and 10 kg." },
      { title: "4.5W operation", description: "Runs all day on a standard outlet." },
      { title: "Set count or full count", description: "Enter a target quantity, run ALL, or work from a List." },
      { title: "Transparent collection bin", description: "See the count, then lift the batch straight into a vial." },
      { title: "AC 110–220V", description: "Accepts 50/60Hz supplies for international installation." },
      { title: "Simple keypad controls", description: "Numeric keypad plus List, ALL, Start and Stop." },
    ],
    features: [
      "Infrared photodetection for tablet-by-tablet verification",
      "Maximum counting speed of 280 tablets per minute",
      "Numeric keypad with List, ALL, Start and Stop controls",
      "Transparent collection bin with front handle",
      "Compact 10 kg benchtop body",
      "4.5W power consumption on AC 110–220V, 50/60Hz",
      "Two-line numeric display",
    ],
    useCases: ["Retail pharmacies", "Hospital outpatient filling", "Cassette and vial replenishment"],
    faqs: [
      { question: "How fast does the Tablet Counter count?", answer: "Up to 280 tablets per minute, depending on tablet size and flow." },
      { question: "How does it verify each tablet?", answer: "Infrared photodetection registers each tablet as it passes the counting path." },
      { question: "Can I count a specific quantity as well as a full bottle?", answer: "Yes. Enter the target quantity on the keypad and press Start, or use ALL to count an entire bottle. List is available for working through multiple quantities." },
      { question: "How much counter space does it need?", answer: "The main body is 130 mm wide, 175 mm deep and 230 mm high and weighs 10 kg." },
      { question: "What are the power requirements?", answer: "4.5W on AC 110–220V, 50/60Hz." },
      { question: "Is this a replacement for a multi-cassette vial packager?", answer: "No. The Tablet Counter counts one medication at a time. For simultaneous multi-prescription vial filling, see the MTC Model." },
    ],
    cta: {
      title: "Count faster without giving up counter space",
      description: "See the Tablet Counter run a set-quantity and full-bottle count on your typical oral solids.",
    },
    relatedSlugs: ["mtc-model", "cap-ex-model", "wap-model"],
  },
];
